version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ATMExpress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    expose:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5021:8080"
    depends_on:
      - postgres